name: Jellytoring api deploy

on: 
  push:
    branches:
    - main
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: '"config-loaded-on-deploy": {}'
        replace: ${{ secrets.APPSETTINGS_CONFIGURATION }}
        include: 'appsettings.json'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Dotnet Publish
      run: dotnet publish -c Release -r linux-x64 -o deploy_folder
    - name: Install OpenVPN
      run: |
        sudo apt update
        sudo apt install -y openvpn openvpn-systemd-resolved
        cat .github/vpn/config.ovpn
    - name: Connect to VPN
      uses: "kota65535/github-openvpn-connect-action@v1"
      with:
        config_file: .github/vpn/config.ovpn
        username: ${{ secrets.OVPN_USERNAME }}
        password: ${{ secrets.OVPN_PASSWORD }}
    - name: stop systemd service
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
        command: sudo systemctl stop jellytoring-api
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "deploy_folder/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
    - name: start systemd service
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
        command: sudo systemctl start jellytoring-api
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
