name: Jellytoring api deploy

on: 
  push:
    branches:
    - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Dotnet Publish
      run: dotnet publish -c Release -r linux-x64
    - name: Install OpenVPN
      run: |
        sudo apt update
        sudo apt install -y openvpn openvpn-systemd-resolved
        cat .github/vpn/config.ovpn
    - name: Connect to VPN
      uses: "kota65535/github-openvpn-connect-action@v1"
      with:
        config_file: .github/vpn/config.ovpn
        username: ${{ secrets.OVPN_USERNAME }}
        password: ${{ secrets.OVPN_PASSWORD }}
    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.5.3
      with:
        local: /home/runner/work/jellytoring-api/jellytoring-api
        remote: ${{ secrets.REMOTE_TARGET }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
    #- name: Run SSH command
     # uses: garygrossgarten/github-action-ssh@v0.3.0
      #with:
       # command: sudo service xxx start
        #host: ${{ secrets.REMOTE_HOST }}
        #username: ${{ secrets.REMOTE_USER }}
        #privateKey: ${{ secrets.REMOTE_SSH_KEY }}
